/**
 * Day 3 — Ratio and Proportion: 20 MCQs + 5 Fill in the Blanks · 25 min
 */
const questions = [
  {
    id: 1,
    type: 'mcq',
    question: 'The ratio of the number of apples to oranges in a basket is 5 : 7. If 10 apples and 6 oranges are added, the ratio becomes 3 : 4. How many apples were there initially?',
    options: ['100', '120', '110', '150'],
    answer: 2,
  },
  {
    id: 2,
    type: 'mcq',
    question: 'If 0.75 : x :: 5 : 8, then x is equal to:',
    options: ['1.12', '1.2', '1.25', '1.30'],
    answer: 1,
  },
  {
    id: 3,
    type: 'mcq',
    question: 'A got twice as many marks in English as in Science. His total marks in English, Science and Mathematics are 180. If the ratio of his marks in English and Mathematics is 2 : 3, what is his marks in Science?',
    options: ['10', '20', '30', '40'],
    answer: 2,
  },
  {
    id: 4,
    type: 'mcq',
    question: 'Two numbers are in the ratio 3 : 5. If 9 is subtracted from each, the new numbers are in the ratio 12 : 23. The smaller number is:',
    options: ['27', '33', '49', '55'],
    answer: 1,
  },
  {
    id: 5,
    type: 'mcq',
    question: "A and B together have Rs. 1,210. If 4/15 of A's amount is equal to 2/5 of B's amount, how much amount does B have?",
    options: ['Rs. 460', 'Rs. 484', 'Rs. 550', 'Rs. 664'],
    answer: 1,
  },
  {
    id: 6,
    type: 'mcq',
    question: 'Seats for Mathematics, Physics and Biology in a school are in the ratio 5 : 7 : 8. There is a proposal to increase these seats by 40%, 50% and 75% respectively. What will be the ratio of increased seats?',
    options: ['2 : 3 : 4', '6 : 7 : 8', '6 : 8 : 9', 'None of these'],
    answer: 0,
  },
  {
    id: 7,
    type: 'mcq',
    question: 'In a bag, there are coins of 25 p, 10 p and 5 p in the ratio of 1 : 2 : 3. If there is Rs. 30 in all, how many 5 p coins are there?',
    options: ['50', '100', '150', '200'],
    answer: 2,
  },
  {
    id: 8,
    type: 'mcq',
    question: 'The ratio of boys to girls appearing in an examination is 4 : 3. Overall, 80% of the candidates passed. If 75% of the boys passed, what percentage of the girls passed?',
    options: ['80%', '83.33%', '86.67%', '90%'],
    answer: 2,
  },
  {
    id: 9,
    type: 'mcq',
    question: 'The present ages of A and B are in the ratio 5 : 7. Eight years ago, their ages were in the ratio 3 : 5. Find their present ages.',
    options: ['20 and 28', '25 and 35', '30 and 42', '35 and 49'],
    answer: 0,
  },
  {
    id: 10,
    type: 'mcq',
    question: "An outgoing batch of students wants to gift books worth Rs 4,200 to their teachers. If the boys offer to pay 50% more than the girls and an external sponsor gives three times the boy's contribution, then how much should the boys donate?",
    options: ['Rs. 600', 'Rs. 840', 'Rs. 900', 'Rs. 1,200'],
    answer: 2,
  },
  {
    id: 11,
    type: 'mcq',
    question: "A and B invested money in a business in the ratio of 7 : 5. If 15% of the total profit goes for charity, and A's share in the profit is Rs. 5,950, then what is the total profit?",
    options: ['Rs. 12,500', 'Rs. 12,000', 'Rs. 10,500', 'Rs. 11,750'],
    answer: 1,
  },
  {
    id: 12,
    type: 'mcq',
    question: 'By mistake, instead of dividing Rs. 117 among A, B and C in the ratio 1/2 : 1/3 : 1/4, it was divided in the ratio of 2 : 3 : 4. Who gains the most and by how much?',
    options: ['Rs. 28', 'Rs. 30', 'Rs. 20', 'Rs. 25'],
    answer: 3,
  },
  {
    id: 13,
    type: 'mcq',
    question: 'A person takes 1/3 of the toffees in a bowl and returns 4 toffees. Another person takes 1/4 of the remaining toffees and returns 3. A third person takes half of the remaining toffees and returns 2. Finally, 17 toffees remain. How many toffees were there initially?',
    options: ['36', '42', '48', '54'],
    answer: 2,
  },
  {
    id: 14,
    type: 'mcq',
    question: 'A recipe requires rice and vegetables in the ratio 7 : 3. If 4 kg more vegetables are added, the ratio becomes 7 : 5. What was the original quantity of rice?',
    options: ['12 kg', '14 kg', '16 kg', '18 kg'],
    answer: 1,
  },
  {
    id: 15,
    type: 'mcq',
    question: "One year ago, the ratio of Harry's age to Peter's age was 5 : 6. After 4 years, this ratio becomes 6 : 7. How old is Peter now?",
    options: ['25 years', '26 years', '31 years', '35 years'],
    answer: 2,
  },
  {
    id: 16,
    type: 'mcq',
    question: 'A container has milk and water in the ratio 7 : 3. If 20 litres of the mixture is removed and replaced with 20 litres of water, the new ratio becomes 7 : 5. What was the initial quantity of the mixture?',
    options: ['100 L', '120 L', '140 L', '160 L'],
    answer: 2,
  },
  {
    id: 17,
    type: 'mcq',
    question: 'If 15 men working 8 hours a day can complete a task in 12 days, how many days will 20 men working 6 hours a day take to complete the same task?',
    options: ['10 days', '12 days', '14 days', '16 days'],
    answer: 1,
  },
  {
    id: 18,
    type: 'mcq',
    question: 'The cost of 18 metres of a certain cloth is ₹2,700. How many metres can be purchased for ₹4,200 at the same rate?',
    options: ['24 m', '26 m', '28 m', '30 m'],
    answer: 2,
  },
  {
    id: 19,
    type: 'mcq',
    question: 'A and B can complete a job in the ratio of their efficiencies 3 : 5. If they work together and earn ₹4,800, what is B\'s share?',
    options: ['₹1,800', '₹2,400', '₹3,000', '₹3,200'],
    answer: 2,
  },
  {
    id: 20,
    type: 'mcq',
    question: 'The ratio of boys to girls in a class is 5 : 4. If 20% of the boys and 25% of the girls are absent, what is the ratio of boys to girls present?',
    options: ['5 : 4', '1 : 1', '4 : 3', '5 : 3'],
    answer: 2,
  },
  {
    id: 21,
    type: 'fill',
    question: 'The cost of 5 kg of sugar is ₹200. Find the cost of 8 kg: ₹______',
    answer: '320',
  },
  {
    id: 22,
    type: 'fill',
    question: 'Two numbers are in the ratio 5 : 6. If their sum is 132, find the larger number: ______',
    answer: '72',
  },
  {
    id: 23,
    type: 'fill',
    question: "The processing time of three modules A, B and C is in the ratio 2 : 3 : 5. If their combined processing time is 200 μs, module C's processing time is ______ μs",
    answer: '100',
  },
  {
    id: 24,
    type: 'fill',
    question: 'A processor executes instructions of three types in the ratio 4 : 3 : 2. Their respective execution times are in the ratio 2 : 3 : 5. What is the ratio of the total execution time contributed by the three instruction types? (Format: a:b:c)',
    answer: '8:9:10',
  },
  {
    id: 25,
    type: 'fill',
    question: 'If x : y = 4 : 7 and y : z = 14 : 15, find x : z. (Format: a:b)',
    answer: '8:15',
  },
];

module.exports = questions;
