/**
 * Day 4 — Averages: 20 MCQs + 5 Fill in the Blanks · 25 min
 */
const questions = [
  {
    id: 1,
    type: 'mcq',
    question: 'If 25a + 25b = 115, what is the average of a and b?',
    options: ['4.6', '5.2', '6.5', '2.3'],
    answer: 3,
  },
  {
    id: 2,
    type: 'mcq',
    question: 'The average of all odd numbers from 1 to 99 is:',
    options: ['49', '49.5', '50', '51'],
    answer: 2,
  },
  {
    id: 3,
    type: 'mcq',
    question: 'The average weight of 6 men is 60 kg. When a new man joins them, the average weight becomes 62 kg. What is the weight of the new man?',
    options: ['72 kg', '74 kg', '76 kg', '70 kg'],
    answer: 1,
  },
  {
    id: 4,
    type: 'mcq',
    question: 'The average run score of a batsman in 10 innings is 40. How many runs must he score in his next inning to raise his average to 45?',
    options: ['90', '95', '85', '100'],
    answer: 1,
  },
  {
    id: 5,
    type: 'mcq',
    question: 'If the mean of a, b, c is M and ab + bc + ca = 0, then the mean of a², b², c² is:',
    options: ['M²', '2M²', '3M²', 'M²/3'],
    answer: 2,
  },
  {
    id: 6,
    type: 'mcq',
    question: 'The average of 2, 7, 6 and x is 5 and the average of 18, 1, 6, x and y is 10. Find y.',
    options: ['15', '18', '20', '22'],
    answer: 2,
  },
  {
    id: 7,
    type: 'mcq',
    question: 'The average of 10 numbers is 30. Later it was observed that numbers 17 and 24 were wrongly taken as 71 and 42. Find the correct average.',
    options: ['21.8', '22.8', '23.8', '24.8'],
    answer: 1,
  },
  {
    id: 8,
    type: 'mcq',
    question: 'The average mark of a student in 5 subjects is 70. One subject mark is increased by 19.5 and another is decreased by 8.5. Find the new average.',
    options: ['70.2', '71.2', '71.8', '72.2'],
    answer: 3,
  },
  {
    id: 9,
    type: 'mcq',
    question: 'The average of 27 numbers is zero. At most, how many of these numbers may be greater than zero?',
    options: ['13', '14', '26', '27'],
    answer: 2,
  },
  {
    id: 10,
    type: 'mcq',
    question: 'The average of 6 numbers is 7. The average of three of them is 5. Find the average of the remaining three numbers.',
    options: ['7', '8', '9', '10'],
    answer: 2,
  },
  {
    id: 11,
    type: 'mcq',
    question: 'The ratio of A to B is 3 : 4 and the average of A, B and C is 40. If the average of A and B is 35, find C.',
    options: ['40', '45', '50', '55'],
    answer: 2,
  },
  {
    id: 12,
    type: 'mcq',
    question: 'In a primary school, 96 students have an average weight of 30 kg. One student leaves and the average weight increases by 200 g. Find the weight of the student who left.',
    options: ['10 kg', '11 kg', '12 kg', '13 kg'],
    answer: 1,
  },
  {
    id: 13,
    type: 'mcq',
    question: 'The average age of 30 students is 16 years. If the oldest student and the youngest student, whose ages differ by 14 years, leave the group, the average age of the remaining 28 students becomes 15.5 years. What is the age of the oldest student?',
    options: ['29 years', '30 years', '31 years', '32 years'],
    answer: 1,
  },
  {
    id: 14,
    type: 'mcq',
    question: 'A car travels from Town A to Town B at a speed of 60 km/h and returns from Town B to Town A at a speed of 40 km/h. What is the average speed of the car for the entire round trip?',
    options: ['48 km/h', '50 km/h', '52 km/h', '45 km/h'],
    answer: 0,
  },
  {
    id: 15,
    type: 'mcq',
    question: 'The average of A and B is 42, and the ratio of A to B is 3 : 4. If C is added, the average of A, B and C becomes 50. Find the value of C.',
    options: ['58', '62', '66', '70'],
    answer: 2,
  },
  {
    id: 16,
    type: 'mcq',
    question: 'The average of n consecutive odd integers is 48. If the smallest number is 3 less than twice the number of integers, which of the following is true about n?',
    options: ['n is a positive integer', 'n is a whole number', 'n is an even integer', 'n is not a whole number'],
    answer: 3,
  },
  {
    id: 17,
    type: 'mcq',
    question: 'The arithmetic mean of the numbers 2/x, 3/x, 4/x, 6/x is 15/8. Find the value of x.',
    options: ['1/2', '1', '2', '4'],
    answer: 2,
  },
  {
    id: 18,
    type: 'mcq',
    question: 'The average of 7 positive integers is 12. What is the maximum possible value of the largest integer if all seven integers are distinct?',
    options: ['60', '65', '63', '71'],
    answer: 2,
  },
  {
    id: 19,
    type: 'mcq',
    question: 'The average of 20 numbers is 35. If 5 numbers whose average is 42 are removed, what is the average of the remaining numbers?',
    options: ['32.67', '15.00', '32.50', '15.25'],
    answer: 0,
  },
  {
    id: 20,
    type: 'mcq',
    question: 'The average of 3 numbers is 20, and the average of 3 other numbers is 30. Find the total sum of all 6 numbers.',
    options: ['140', '145', '150', '155'],
    answer: 2,
  },
  {
    id: 21,
    type: 'fill',
    question: 'The average of 8 numbers is 24. If one of the numbers is 31, then the average of the remaining 7 numbers is _____.',
    answer: '23',
  },
  {
    id: 22,
    type: 'fill',
    question: 'The average age of 12 students is 18 years. When a teacher joins the group, the average age becomes 20 years. The age of the teacher is _____ years.',
    answer: '44',
  },
  {
    id: 23,
    type: 'fill',
    question: 'The average of 15 consecutive integers is 42. If the largest integer is removed, the average of the remaining 14 integers becomes _____.',
    answer: '41.5',
  },
  {
    id: 24,
    type: 'fill',
    question: 'The average marks of 40 students is 62. If the marks of two students, originally recorded as 48 and 73, were mistakenly recorded as 84 and 37 respectively, the correct average of the class is _____.',
    answer: '62',
  },
  {
    id: 25,
    type: 'fill',
    question: 'The average of 11 numbers is 48. The average of the first 6 numbers is 42, while the average of the last 6 numbers is 55. The 6th number is _____.',
    answer: '54',
  },
];

module.exports = questions;
